plugins {
    id 'com.gradleup.shadow' version '9.3.1'
}

description = 'Ezlib'

allprojects {
    apply plugin: 'java'
    apply plugin: 'idea'
    apply from: "$rootDir/gradle/publish-config.gradle"

    idea {
        module {
            downloadJavadoc = true
            downloadSources = true
        }
    }

    repositories {
        mavenCentral()
    }

    compileJava {
        options.encoding = 'UTF-8'
        options.compilerArgs.add('-XDenableSunApiLintControl')
    }

    java {
        toolchain.languageVersion.set(JavaLanguageVersion.of(8))
        withSourcesJar()
        withJavadocJar()
    }
}

jar {
    enabled = false
    dependsOn (shadowJar)
}

shadowJar {
    archiveClassifier.set('')
    relocate 'project.version', (System.getenv("VERSION") ?: project.version)
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.shadow

            afterEvaluate {
                artifact tasks.named('sourcesJar')
                artifact tasks.named('javadocJar')
            }
        }
    }
}

def javadocProjects= [
        ':',
        ':annotations',
        ':loader'
]

tasks.register('allJavadoc', Javadoc) {
    source javadocProjects.collect { project(it).sourceSets.main.allJava }
    classpath = files(javadocProjects.collect { project(it).sourceSets.main.compileClasspath })
    options {
        links 'https://docs.oracle.com/en/java/javase/11/docs/api/'
    }
    destinationDir = file(project.layout.buildDirectory.dir('docs/all-javadoc'))
}