plugins {
    id 'com.gradleup.shadow' version '9.3.1'
}

description = 'Ezlib'

allprojects {
    apply plugin: 'java'
    apply plugin: 'idea'
    apply from: "$rootDir/gradle/publish-config.gradle"

    idea {
        module {
            downloadJavadoc = true
            downloadSources = true
        }
    }

    repositories {
        mavenCentral()
    }

    compileJava {
        options.encoding = 'UTF-8'
        options.compilerArgs.add('-XDenableSunApiLintControl')
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
        withSourcesJar()
        withJavadocJar()
    }

    javadoc {
        options {
            links 'https://docs.oracle.com/en/java/javase/25/docs/api/'
        }
    }
}

jar {
    enabled = false
    dependsOn (shadowJar)
}

shadowJar {
    archiveClassifier.set('')
    relocate 'project.version', (System.getenv("VERSION") ?: project.version)
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.shadow

            afterEvaluate {
                artifact tasks.named('sourcesJar')
                artifact tasks.named('javadocJar')
            }
        }
    }
}

def javadocProjects= [
        ':',
        ':annotations',
        ':loader'
]

tasks.register('allJavadoc', Javadoc) {
    group = 'documentation'

    source javadocProjects.collect { project(it).sourceSets.main.allJava }
    classpath = files(javadocProjects.collect { project(it).sourceSets.main.compileClasspath })
    javadocTool.set(javaToolchains.javadocToolFor {
        languageVersion.set(JavaLanguageVersion.of(25))
    })

    options {
        def allLinks = javadocProjects.collect { projectPath ->
            project(projectPath).javadoc.options.links
        }.flatten().unique()
        allLinks.each { link -> links link }
    }

    destinationDir = file(project.layout.buildDirectory.dir('docs/all-javadoc'))
}