plugins {
    id 'java-library'
}

description = 'Ezlib Loader'

dependencies {
    api project(':')
    compileOnlyApi project(':annotations')
    compileOnly 'com.google.code.gson:gson:2.13.2'
    compileOnly 'org.yaml:snakeyaml:2.5'

    testImplementation(platform('org.junit:junit-bom:5.14.2'))
    testImplementation('org.junit.jupiter:junit-jupiter')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}