plugins {
    id 'com.gradleup.shadow'
}

description = 'Ezlib Internal'

dependencies {
    implementation('me.lucko:jar-relocator:1.7') { transitive = false }
    implementation 'org.ow2.asm:asm-commons:9.9.1'
}

jar {
    enabled = false
    dependsOn (shadowJar)
}

shadowJar {
    archiveClassifier.set('')
    relocate 'com.saicone.ezlib.internal', 'com.saicone.ezlib.internal.' + (System.getenv("VERSION") ?: project.version)
    relocate 'org.objectweb.asm', 'com.saicone.ezlib.asm.9.9.1'
    relocate 'me.lucko.jarrelocator', 'com.saicone.ezlib.relocator.1.7'
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.shadow

            afterEvaluate {
                artifact tasks.named('sourcesJar')
                artifact tasks.named('javadocJar')
            }
        }
    }
}